/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodpassignment1;

import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author User
 */
public class placesFrame extends javax.swing.JFrame {

    /**
     * Creates new form placesFrame
     */
    public placesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                addTab(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    protected JComponent makeTextPanel(String placeName, String placeDesc, String placeLoc, String placeImg) {
    JPanel panel = new JPanel(false);
    
    Font myTextFont = new Font("Tempus Sans ITC", Font.PLAIN,20);
       
        JTextArea placesNames = new JTextArea("Town: "+placeName+"\n"
                                            +"\n"+"Town Description: "+placeDesc+"\n"
                                            +"\n"+"Town History: "+placeLoc);   
        placesNames.setFont(myTextFont);
        placesNames.setWrapStyleWord(true);
        placesNames.setLineWrap(true);
        placesNames.setEditable(false);
        placesNames.setFocusable(false);
        placesNames.setOpaque(false);
        ImageIcon image = new ImageIcon(getClass().getResource("image/"+placeImg));
        JLabel placesImg = new JLabel(image);
        panel.setLayout(new GridLayout(2, 1));
        placesImg.setHorizontalAlignment(JLabel.CENTER);
         
        panel.setLayout(new GridLayout(2, 0));
        panel.add(new JScrollPane(placesImg,
                        ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED,
                        ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER)); 
        panel.add(new JScrollPane(placesNames,
                        ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED,
                        ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER));  
    
    return panel;
  }  
    private void addTab(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_addTab
        // TODO add your handling code here:
        Towns town = new Towns();
        town.setTowns();
        
        InterestingPlaces townPlace = new InterestingPlaces();
        townPlace.setPlaces();
        
        
        int i;
        
        String test = townFrame.townName.getText();        
         
        
        for(i = 0; i < townPlace.getAllPlaceName(test).length; i++){
            if(townPlace.getAllPlaceName(test)[i]!=null){
                
                JComponent panel1 = makeTextPanel(townPlace.getAllPlaceName(test)[i]
                                    ,townPlace.getAllPlaceDesc(test)[i]
                                    ,townPlace.getAllPlaceLoc(test)[i]
                                    ,townPlace.getAllPlaceImg(test)[i]);               
                
                
                jTabbedPane1.addTab(townPlace.getAllPlaceName(test)[i], panel1);               
            }           
        }
    }//GEN-LAST:event_addTab

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new townFrame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(placesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(placesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(placesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(placesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new placesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
